// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/interface_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	uripath "go.innotegrity.dev/mod/uripath"
	xerrors "go.innotegrity.dev/mod/xerrors"
	gomock "go.uber.org/mock/gomock"
)

// MockURIPathBackend is a mock of URIPathBackend interface.
type MockURIPathBackend struct {
	ctrl     *gomock.Controller
	recorder *MockURIPathBackendMockRecorder
	isgomock struct{}
}

// MockURIPathBackendMockRecorder is the mock recorder for MockURIPathBackend.
type MockURIPathBackendMockRecorder struct {
	mock *MockURIPathBackend
}

// NewMockURIPathBackend creates a new mock instance.
func NewMockURIPathBackend(ctrl *gomock.Controller) *MockURIPathBackend {
	mock := &MockURIPathBackend{ctrl: ctrl}
	mock.recorder = &MockURIPathBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURIPathBackend) EXPECT() *MockURIPathBackendMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURIPathBackend) Delete(ctx context.Context, options ...map[string]any) xerrors.Error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(xerrors.Error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURIPathBackendMockRecorder) Delete(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURIPathBackend)(nil).Delete), varargs...)
}

// Exists mocks base method.
func (m *MockURIPathBackend) Exists(ctx context.Context, options ...map[string]any) (bool, xerrors.Error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(xerrors.Error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockURIPathBackendMockRecorder) Exists(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockURIPathBackend)(nil).Exists), varargs...)
}

// Get mocks base method.
func (m *MockURIPathBackend) Get(ctx context.Context, options ...map[string]any) ([]byte, xerrors.Error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(xerrors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURIPathBackendMockRecorder) Get(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURIPathBackend)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockURIPathBackend) List(ctx context.Context, recurse bool, options ...map[string]any) ([]string, xerrors.Error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, recurse}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(xerrors.Error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockURIPathBackendMockRecorder) List(ctx, recurse any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, recurse}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockURIPathBackend)(nil).List), varargs...)
}

// Options mocks base method.
func (m *MockURIPathBackend) Options() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Options")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockURIPathBackendMockRecorder) Options() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockURIPathBackend)(nil).Options))
}

// Put mocks base method.
func (m *MockURIPathBackend) Put(ctx context.Context, data []byte, options ...map[string]any) xerrors.Error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, data}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(xerrors.Error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockURIPathBackendMockRecorder) Put(ctx, data any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, data}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockURIPathBackend)(nil).Put), varargs...)
}

// RemoveAllOptions mocks base method.
func (m *MockURIPathBackend) RemoveAllOptions() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveAllOptions")
}

// RemoveAllOptions indicates an expected call of RemoveAllOptions.
func (mr *MockURIPathBackendMockRecorder) RemoveAllOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllOptions", reflect.TypeOf((*MockURIPathBackend)(nil).RemoveAllOptions))
}

// RemoveOption mocks base method.
func (m *MockURIPathBackend) RemoveOption(key string) uripath.URIPathBackend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOption", key)
	ret0, _ := ret[0].(uripath.URIPathBackend)
	return ret0
}

// RemoveOption indicates an expected call of RemoveOption.
func (mr *MockURIPathBackendMockRecorder) RemoveOption(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOption", reflect.TypeOf((*MockURIPathBackend)(nil).RemoveOption), key)
}

// ReplaceOptions mocks base method.
func (m *MockURIPathBackend) ReplaceOptions(options map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReplaceOptions", options)
}

// ReplaceOptions indicates an expected call of ReplaceOptions.
func (mr *MockURIPathBackendMockRecorder) ReplaceOptions(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceOptions", reflect.TypeOf((*MockURIPathBackend)(nil).ReplaceOptions), options)
}

// SetOption mocks base method.
func (m *MockURIPathBackend) SetOption(key string, value any) uripath.URIPathBackend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOption", key, value)
	ret0, _ := ret[0].(uripath.URIPathBackend)
	return ret0
}

// SetOption indicates an expected call of SetOption.
func (mr *MockURIPathBackendMockRecorder) SetOption(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOption", reflect.TypeOf((*MockURIPathBackend)(nil).SetOption), key, value)
}

// URIPath mocks base method.
func (m *MockURIPathBackend) URIPath() *uripath.URIPath {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URIPath")
	ret0, _ := ret[0].(*uripath.URIPath)
	return ret0
}

// URIPath indicates an expected call of URIPath.
func (mr *MockURIPathBackendMockRecorder) URIPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URIPath", reflect.TypeOf((*MockURIPathBackend)(nil).URIPath))
}

// MockS3ClientAPI is a mock of S3ClientAPI interface.
type MockS3ClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientAPIMockRecorder
	isgomock struct{}
}

// MockS3ClientAPIMockRecorder is the mock recorder for MockS3ClientAPI.
type MockS3ClientAPIMockRecorder struct {
	mock *MockS3ClientAPI
}

// NewMockS3ClientAPI creates a new mock instance.
func NewMockS3ClientAPI(ctrl *gomock.Controller) *MockS3ClientAPI {
	mock := &MockS3ClientAPI{ctrl: ctrl}
	mock.recorder = &MockS3ClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ClientAPI) EXPECT() *MockS3ClientAPIMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockS3ClientAPI) DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObject", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3ClientAPIMockRecorder) DeleteObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockS3ClientAPI)(nil).DeleteObject), varargs...)
}

// GetObject mocks base method.
func (m *MockS3ClientAPI) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3ClientAPIMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3ClientAPI)(nil).GetObject), varargs...)
}

// HeadObject mocks base method.
func (m *MockS3ClientAPI) HeadObject(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HeadObject", varargs...)
	ret0, _ := ret[0].(*s3.HeadObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockS3ClientAPIMockRecorder) HeadObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockS3ClientAPI)(nil).HeadObject), varargs...)
}

// ListObjectsV2 mocks base method.
func (m *MockS3ClientAPI) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListObjectsV2", varargs...)
	ret0, _ := ret[0].(*s3.ListObjectsV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsV2 indicates an expected call of ListObjectsV2.
func (mr *MockS3ClientAPIMockRecorder) ListObjectsV2(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsV2", reflect.TypeOf((*MockS3ClientAPI)(nil).ListObjectsV2), varargs...)
}

// PutObject mocks base method.
func (m *MockS3ClientAPI) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3ClientAPIMockRecorder) PutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3ClientAPI)(nil).PutObject), varargs...)
}
